<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-08-08T12:19:40 IST" name="Default suite" finished-at="2023-08-08T12:19:57 IST" duration-ms="16626">
    <groups>
    </groups>
    <test started-at="2023-08-08T12:19:40 IST" name="Default test" finished-at="2023-08-08T12:19:57 IST" duration-ms="16626">
      <class name="AdminModuleTestScripts.AdminModule">
        <test-method is-config="true" signature="initializeChrome()[pri:0, instance:AdminModuleTestScripts.AdminModule@55141def]" started-at="2023-08-08T12:19:41 IST" name="initializeChrome" finished-at="2023-08-08T12:19:43 IST" duration-ms="2130" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initializeChrome -->
        <test-method signature="CreateTeamLevel()[pri:2, instance:AdminModuleTestScripts.AdminModule@55141def]" started-at="2023-08-08T12:19:43 IST" name="CreateTeamLevel" description="This testcase verifies to create a TeamLevel" finished-at="2023-08-08T12:19:57 IST" duration-ms="13783" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Level Number] but found [Don't Forget]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Level Number] but found [Don't Forget]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at AdminModuleTestScripts.AdminModule.CreateTeamLevel(AdminModule.java:61)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CreateTeamLevel -->
      </class> <!-- AdminModuleTestScripts.AdminModule -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
